stages:
  - push

services:
  - name: docker:dind
    command: [ "--tls=false" ]

variables:
  GIT_SSL_NO_VERIFY: "true"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

before_script:
  - mkdir $HOME/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)\"}}}" > $HOME/.docker/config.json


push:
  image: docker/compose:latest
  stage: push
  script:
    - export TAG=${CI_COMMIT_TAG-latest}
    - docker-compose build -t "registry.gitlab.com/apps-lab/kiwi/services/ml/models/dalai:latest"
    - docker-compose push
