version: '3.7'
services:
  dalai:
    image: registry.gitlab.com/apps-lab/kiwi/services/ml/models/dalai:latest
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./models/alpaca:/root/dalai/alpaca
      - ./models/llama:/root/dalai/llama
